#!/usr/bin/env python3
"""Offline Linux/x86_64 Canon reference oracle; never opens a printer."""
import argparse
import ctypes as C
import hashlib
import json
import os
from pathlib import Path
import platform
import subprocess
import tarfile
import urllib.request

URL = "https://gdlp01.c-wss.com/gds/0/0100005950/10/linux-UFRIILT-drv-v500-uken-18.tar.gz"
SHA256 = "46888140016bc1096694a0fd6fd3f6ad393970b8153756373a382dc82390f259"
HERE = Path(__file__).resolve().parent


def prepare(root):
    if platform.system() != "Linux" or platform.machine() != "x86_64":
        raise RuntimeError("This reference oracle requires Linux/x86_64, not Android")
    root.mkdir(parents=True, exist_ok=True)
    archive = root / "canon-v500.tar.gz"
    if not archive.exists():
        temporary = root / "download.part"
        try:
            with urllib.request.urlopen(URL, timeout=30) as response, temporary.open("wb") as output:
                total = 0
                while block := response.read(1024 * 1024):
                    total += len(block)
                    if total > 128 * 1024 * 1024:
                        raise RuntimeError("Reference archive exceeds download limit")
                    output.write(block)
            temporary.replace(archive)
        finally:
            temporary.unlink(missing_ok=True)
    if hashlib.sha256(archive.read_bytes()).hexdigest() != SHA256:
        raise RuntimeError("Canon reference archive checksum mismatch")
    unpacked = root / "linux-UFRIILT-drv-v500-uken"
    if not unpacked.exists():
        with tarfile.open(archive) as package:
            package.extractall(root, filter="data")
    lib = root / "binary/usr/lib"
    if not (lib / "libcanon_slimsfp.so.1.0.0").exists():
        subprocess.run(["dpkg-deb", "-x", str(unpacked / "64-bit_Driver/Debian/cnrdrvcups-ufr2lt-uk_5.00-1_amd64.deb"), str(root / "binary")], check=True)
    # Modern Debian's libcups also exports the legacy raster entry points.
    shim = lib / "libcupsimage.so.2"
    system_cups = Path("/lib/x86_64-linux-gnu/libcups.so.2")
    if not shim.exists() and system_cups.exists():
        shim.symlink_to(system_cups)
    subprocess.run(["gcc", "-shared", "-fPIC", "-o", str(root / "pathmap.so"), str(HERE / "pathmap.c"), "-ldl"], check=True)
    ppd = (root / "binary/usr/share/cups/model/CNRCUPSLBP6030ZNK.ppd").read_text()
    ppd = ppd.replace("/usr/lib/Canon/CUPS_SFPR", str(lib / "Canon/CUPS_SFPR"))
    (root / "lbp6030-reference.ppd").write_text(ppd)
    return lib


def generate(root):
    lib = prepare(root)
    source = root / "reference.ps"
    source.write_text("""%!PS-Adobe-3.0
<< /PageSize [595.3 841.9] >> setpagedevice
/Helvetica findfont 36 scalefont setfont
72 720 moveto (Canon reference test) show
72 600 180 12 rectfill
showpage
""")
    raster = root / "reference.raster"
    subprocess.run(["gs", "-q", "-dBATCH", "-dNOPAUSE", "-sDEVICE=cups", "-r600", "-dDEVICEWIDTHPOINTS=595.3", "-dDEVICEHEIGHTPOINTS=841.9", "-dcupsColorSpace=0", "-dcupsBitsPerColor=8", "-sOutputFile=" + str(raster), str(source)], check=True, timeout=60)
    output = root / "reference-ncap-pdl.prn"
    env = os.environ | {
        "CANON_REFERENCE_ROOT": str(root),
        "LD_PRELOAD": str(root / "pathmap.so"),
        "LD_LIBRARY_PATH": str(lib),
        "PPD": str(root / "lbp6030-reference.ppd"),
        "DEVICE_URI": "file://" + str(output),
    }
    with output.open("wb") as stream, (root / "reference-filter.log").open("wb") as log:
        subprocess.run([str(lib / "cups/filter/rastertosfp"), "1", "reference", "Canon test", "1", "PageSize=A4 Resolution=600", str(raster)], env=env, stdout=stream, stderr=log, check=True, timeout=60)
    encoded = output.read_bytes()
    if not encoded.startswith(bytes.fromhex("01 c1 85")) or not encoded.endswith(bytes.fromhex("13 12 11")):
        raise RuntimeError("Reference filter did not produce the expected NCAP PDL framing")
    result = {
        "driverArchiveSha256": SHA256,
        "output": output.name,
        "sha256": hashlib.sha256(encoded).hexdigest(),
        "bytes": len(encoded),
        "evidence": "Generated by Canon page filter in no-session mode; no printer attached",
        "cpcaSessionCaptured": False,
        "physicalPrintVerified": False,
    }
    (root / "reference-manifest.json").write_text(json.dumps(result, indent=2) + "\n")
    print(json.dumps(result, indent=2))


def verify_slim(root):
    lib = prepare(root)
    oracle = C.CDLL(str(lib / "libcanon_slimsfp.so.1.0.0"))
    byte = C.c_ubyte
    pointer = C.POINTER(byte)
    oracle.lCaptDecode.argtypes = [C.POINTER(pointer), pointer, C.c_int, C.c_int, C.POINTER(C.c_int), C.c_int, pointer]
    oracle.lCaptDecode.restype = C.c_int
    # Canon LBP6030 PPD's SLIM settings: 3,9,6,1,0,0,80 (last field is LE16).
    params = (byte * 8)(3, 9, 6, 1, 0, 0, 80, 0)
    passed = 0
    for line in (HERE / "slim-literal-vectors.tsv").read_text().splitlines():
        if not line or line.startswith("#"):
            continue
        name, stride, rows, depth, raw_hex, encoded_hex = line.split("\t")
        stride, rows, depth = int(stride), int(rows), int(depth)
        raw, encoded = bytes.fromhex(raw_hex), bytes.fromhex(encoded_hex)
        assert 0 < len(raw) <= 100 * 1024 and len(raw) == stride * rows
        incoming = (byte * (len(encoded) + 8)).from_buffer_copy(encoded + bytes(8))
        start = C.cast(incoming, pointer)
        outgoing = (byte * (len(raw) + 16))(*([0xaa] * (len(raw) + 16)))
        remaining = C.c_int(len(encoded))
        decoded_rows = oracle.lCaptDecode(C.byref(start), outgoing, stride, rows, C.byref(remaining), depth, params)
        assert decoded_rows == rows, (name, decoded_rows)
        assert bytes(outgoing[:len(raw)]) == raw, name
        assert bytes(outgoing[len(raw):]) == bytes([0xaa] * 16), name
        assert 0 <= remaining.value <= 4, (name, remaining.value)
        passed += 1
    result = {"oracle": "Canon v5.00 lCaptDecode", "driverArchiveSha256": SHA256, "fixturesPassed": passed, "physicalPrintVerified": False}
    (root / "slim-oracle-results.json").write_text(json.dumps(result, indent=2) + "\n")
    print(json.dumps(result, indent=2))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=["prepare", "generate", "verify-slim"])
    parser.add_argument("--work-dir", type=Path, required=True, help="External scratch directory; driver binaries must not be committed")
    args = parser.parse_args()
    root = args.work_dir.expanduser().resolve()
    if root == HERE or HERE in root.parents:
        parser.error("Use a scratch directory outside tools/canon")
    {"prepare": prepare, "generate": generate, "verify-slim": verify_slim}[args.action](root)


if __name__ == "__main__":
    main()
