#!/usr/bin/env python3
"""Offline Linux/x86_64 Canon reference oracle; never opens a printer."""
import argparse
import ctypes as C
import hashlib
import json
import os
from pathlib import Path
import platform
import subprocess
import signal
import struct
import math
import tarfile
import gzip
import urllib.request

URL = "https://gdlp01.c-wss.com/gds/0/0100005950/10/linux-UFRIILT-drv-v500-uken-18.tar.gz"
SHA256 = "46888140016bc1096694a0fd6fd3f6ad393970b8153756373a382dc82390f259"
HERE = Path(__file__).resolve().parent


def prepare(root):
    if platform.system() != "Linux" or platform.machine() != "x86_64":
        raise RuntimeError("This reference oracle requires Linux/x86_64, not Android")
    root.mkdir(parents=True, exist_ok=True)
    archive = root / "canon-v500.tar.gz"
    if not archive.exists():
        temporary = root / "download.part"
        try:
            with urllib.request.urlopen(URL, timeout=30) as response, temporary.open("wb") as output:
                total = 0
                while block := response.read(1024 * 1024):
                    total += len(block)
                    if total > 128 * 1024 * 1024:
                        raise RuntimeError("Reference archive exceeds download limit")
                    output.write(block)
            temporary.replace(archive)
        finally:
            temporary.unlink(missing_ok=True)
    if hashlib.sha256(archive.read_bytes()).hexdigest() != SHA256:
        raise RuntimeError("Canon reference archive checksum mismatch")
    unpacked = root / "linux-UFRIILT-drv-v500-uken"
    if not unpacked.exists():
        with tarfile.open(archive) as package:
            package.extractall(root, filter="data")
    lib = root / "binary/usr/lib"
    if not (lib / "libcanon_slimsfp.so.1.0.0").exists():
        subprocess.run(["dpkg-deb", "-x", str(unpacked / "64-bit_Driver/Debian/cnrdrvcups-ufr2lt-uk_5.00-1_amd64.deb"), str(root / "binary")], check=True)
    # Modern Debian's libcups also exports the legacy raster entry points.
    shim = lib / "libcupsimage.so.2"
    system_cups = Path("/lib/x86_64-linux-gnu/libcups.so.2")
    if not shim.exists() and system_cups.exists():
        shim.symlink_to(system_cups)
    subprocess.run(["gcc", "-shared", "-fPIC", "-o", str(root / "pathmap.so"), str(HERE / "pathmap.c"), "-ldl"], check=True)
    ppd = (root / "binary/usr/share/cups/model/CNRCUPSLBP6030ZNK.ppd").read_text()
    ppd = ppd.replace("/usr/lib/Canon/CUPS_SFPR", str(lib / "Canon/CUPS_SFPR"))
    (root / "lbp6030-reference.ppd").write_text(ppd)
    for name in ("session_recorder", "pdl_recorder"):
        subprocess.run(["gcc", "-shared", "-fPIC", "-o", str(root / (name + ".so")), str(HERE / (name + ".c")), "-ldl"], check=True)
    return lib


def generate(root):
    lib = prepare(root)
    source = root / "reference.ps"
    source.write_text("""%!PS-Adobe-3.0
<< /PageSize [595.3 841.9] >> setpagedevice
/Helvetica findfont 36 scalefont setfont
72 720 moveto (Canon reference test) show
72 600 180 12 rectfill
showpage
""")
    raster = root / "reference.raster"
    subprocess.run(["gs", "-q", "-dBATCH", "-dNOPAUSE", "-sDEVICE=cups", "-r600", "-dDEVICEWIDTHPOINTS=595.3", "-dDEVICEHEIGHTPOINTS=841.9", "-dcupsColorSpace=0", "-dcupsBitsPerColor=8", "-sOutputFile=" + str(raster), str(source)], check=True, timeout=60)
    output = root / "reference-ncap-pdl.prn"
    env = os.environ | {
        "CANON_REFERENCE_ROOT": str(root),
        "LD_PRELOAD": str(root / "pathmap.so"),
        "LD_LIBRARY_PATH": str(lib),
        "PPD": str(root / "lbp6030-reference.ppd"),
        "DEVICE_URI": "file://" + str(output),
    }
    with output.open("wb") as stream, (root / "reference-filter.log").open("wb") as log:
        subprocess.run([str(lib / "cups/filter/rastertosfp"), "1", "reference", "Canon test", "1", "PageSize=A4 Resolution=600", str(raster)], env=env, stdout=stream, stderr=log, check=True, timeout=60)
    encoded = output.read_bytes()
    if not encoded.startswith(bytes.fromhex("01 c1 85")) or not encoded.endswith(bytes.fromhex("13 12 11")):
        raise RuntimeError("Reference filter did not produce the expected NCAP PDL framing")
    result = {
        "driverArchiveSha256": SHA256,
        "output": output.name,
        "sha256": hashlib.sha256(encoded).hexdigest(),
        "bytes": len(encoded),
        "evidence": "Generated by Canon page filter in no-session mode; no printer attached",
        "cpcaSessionCaptured": False,
        "physicalPrintVerified": False,
    }
    (root / "reference-manifest.json").write_text(json.dumps(result, indent=2) + "\n")
    print(json.dumps(result, indent=2))


def verify_slim(root):
    lib = prepare(root)
    oracle = C.CDLL(str(lib / "libcanon_slimsfp.so.1.0.0"))
    byte = C.c_ubyte
    pointer = C.POINTER(byte)
    oracle.lCaptDecode.argtypes = [C.POINTER(pointer), pointer, C.c_int, C.c_int, C.POINTER(C.c_int), C.c_int, pointer]
    oracle.lCaptDecode.restype = C.c_int
    # Canon LBP6030 PPD's SLIM settings: 3,9,6,1,0,0,80 (last field is LE16).
    params = (byte * 8)(3, 9, 6, 1, 0, 0, 80, 0)
    passed = 0
    literal_lines = (HERE / "slim-literal-vectors.tsv").read_text().splitlines()
    copy_lines = gzip.decompress((HERE / "slim-copy-vectors.tsv.gz").read_bytes()).decode().splitlines()
    for line in literal_lines + copy_lines:
        if not line or line.startswith("#"):
            continue
        fields = line.split("\t")
        name, stride, rows, depth, raw_hex, encoded_hex = fields[:6]
        stride, rows, depth = int(stride), int(rows), int(depth)
        raw, encoded = bytes.fromhex(raw_hex), bytes.fromhex(encoded_hex)
        assert 0 < len(raw) <= 100 * 1024 and len(raw) == stride * rows
        assert len(encoded) % 4 == 0
        assert slim_end_code(encoded) == (int(fields[6]) if len(fields) == 7 else 0), name
        incoming = (byte * (len(encoded) + 8)).from_buffer_copy(encoded + bytes(8))
        start = C.cast(incoming, pointer)
        outgoing = (byte * (len(raw) + 16))(*([0xaa] * (len(raw) + 16)))
        remaining = C.c_int(len(encoded))
        decoded_rows = oracle.lCaptDecode(C.byref(start), outgoing, stride, rows, C.byref(remaining), depth, params)
        assert decoded_rows == rows, (name, decoded_rows)
        assert bytes(outgoing[:len(raw)]) == raw, name
        assert bytes(outgoing[len(raw):]) == bytes([0xaa] * 16), name
        assert 0 <= remaining.value <= 4, (name, remaining.value)
        passed += 1
    assert passed == 172, ("Missing SLIM fixtures", passed)
    result = {"oracle": "Canon v5.00 lCaptDecode", "driverArchiveSha256": SHA256, "fixturesPassed": passed,
              "literalFixturesPassed": 60, "copyFixturesPassed": 112, "physicalPrintVerified": False}
    (root / "slim-oracle-results.json").write_text(json.dumps(result, indent=2) + "\n")
    print(json.dumps(result, indent=2))


def cpca_packets(stream):
    packets, offset = [], 0
    while offset < len(stream):
        assert len(stream) - offset >= 20, "Truncated CPCA header"
        header = stream[offset:offset + 20]
        assert header[:4] == bytes.fromhex("cdca1000"), "Unexpected CPCA mode"
        assert header[6:8] == bytes(2), "Unexpected CPCA sequence mode"
        assert header[10:] == bytes.fromhex("ffff0000000000000000"), "Unexpected CPCA user ID"
        command, length = struct.unpack_from(">H2xH", header, 4)
        assert offset + 20 + length <= len(stream), "Truncated CPCA payload"
        packets.append((command, stream[offset + 20:offset + 20 + length]))
        offset += 20 + length
    return packets


def slim_end_code(encoded):
    # The official page filter pads its end token with ones. Discard padding,
    # including the low one in FE/01, to distinguish page end from band end.
    bits = ''.join(f'{value ^ 0x43:08b}' for value in encoded).rstrip('1')
    if bits.endswith('1111111000'):
        return 0
    if bits.endswith('111111100'):
        return 1
    raise AssertionError('Missing SLIM band/page end control')


def verify_reference_page_end(pdl):
    bands, offset = [], 54
    width, height = struct.unpack_from('>HH', pdl, 33)
    y = 0
    while y < height:
        assert pdl[offset:offset + 3] == bytes.fromhex('62e385')
        bw, rows = struct.unpack_from('>HH', pdl, offset + 3)
        assert bw == width and struct.unpack_from('>H', pdl, offset + 11)[0] == y
        length = struct.unpack_from('>H', pdl, offset + 17)[0]
        payload = pdl[offset + 22:offset + 22 + length]
        last = y + rows == height
        assert payload[:8] == bytes.fromhex('0309060100005000')
        assert payload[8] == (0 if last else 1), 'Official band continuation flag changed'
        code = slim_end_code(payload[13:-1])
        assert code == int(last), 'Official SLIM end control changed'
        bands.append({'rows': rows, 'y': y, 'continuation': payload[8], 'endCode': code})
        y += rows
        offset += 22 + length
    assert pdl[offset:] == bytes.fromhex('131211')
    return bands


def verify_protocol(root):
    lib = prepare(root)
    output = root / "reference-cpca-job.prn"
    output.unlink(missing_ok=True)
    # Reuse the page raster generated by the normal reference command. Stub Info
    # initialization and all I/O, so even an installed Canon backend is never used.
    if not (root / "reference.raster").exists():
        generate(root)
    env = os.environ | {
        "CANON_REFERENCE_ROOT": str(root), "CANON_CPCA_CAPTURE": str(output),
        "CANON_CAPTURE_PPD": str(root / "lbp6030-reference.ppd"), "PRINTER": "reference",
        "LD_PRELOAD": str(root / "session_recorder.so"),
        "LD_LIBRARY_PATH": str(lib) + ":" + str(lib / "Canon/CUPS_SFPR/Libs"),
        "PPD": str(root / "lbp6030-reference.ppd"), "DEVICE_URI": "usb://Canon/LBP6030?serial=reference",
    }
    with (root / "cpca-filter.log").open("wb") as log:
        process = subprocess.Popen([str(lib / "cups/filter/rastertosfp"), "1", "reference", "Canon test", "1", "PageSize=A4 Resolution=600", str(root / "reference.raster")], env=env, stdout=subprocess.DEVNULL, stderr=log, start_new_session=True)
        try:
            assert process.wait(timeout=60) == 0
        except subprocess.TimeoutExpired:
            os.killpg(process.pid, signal.SIGKILL)
            process.wait()
            raise
    actual = cpca_packets(output.read_bytes())
    expected = []
    fixtures = HERE.parents[1] / "app/src/test/resources/canon"
    for line in (fixtures / "cpca-module-packets.tsv").read_text().splitlines():
        if line and not line.startswith("#"):
            command, payload = line.split("\t")
            expected.append((int(command), bytes.fromhex(payload) if payload != "-" else b""))
    fixed = [(command, payload) for command, payload in actual if command != 0x1a]
    assert len(fixed) == len(expected)
    for i, ((command, payload), (reference_command, reference_payload)) in enumerate(zip(fixed, expected)):
        assert command == reference_command
        if i != 0:  # JobStart metadata includes the machine UUID/hostname and time.
            assert payload == reference_payload, (i, command)
    assert any(command == 0x1a for command, _ in actual)

    recorder = C.CDLL(str(root / "pdl_recorder.so"), mode=C.RTLD_GLOBAL)
    recorder.recorder_bytes.restype = C.POINTER(C.c_ubyte)
    C.CDLL(str(lib / "libcanon_slimsfp.so.1.0.0"), mode=C.RTLD_GLOBAL)
    C.CDLL(str(lib / "libcaepcmsfp.so.1"), mode=C.RTLD_GLOBAL)
    native = C.CDLL(str(lib / "libcanonncapr.so.1.0.0"))
    context = (C.c_ubyte * 4096)()
    attributes = (C.c_ubyte * 64)()
    for offset, value in ((0x14, 229), (0x64, 0x22114), (0x478, 2), (0x1c, 4992), (0x30, 7016)):
        C.c_uint32.from_buffer(context, offset).value = value
    def capture(name, *args):
        recorder.recorder_reset()
        method = getattr(native, name)
        method.restype = C.c_ubyte
        assert method(context, *args) == 1
        return bytes(recorder.recorder_bytes()[:recorder.recorder_size()])
    blob = (C.c_ubyte * 4)(1, 2, 3, 4)
    frames = {
        "job": capture("pdbdlBeginJob", 600),
        "paper2": capture("pdbdlBeginMedia", 2, -1, 0),
        "paper3": capture("pdbdlBeginMedia", 3, -1, 0),
        "paper6": capture("pdbdlBeginMedia", 6, -1, 0),
        "source": capture("pdbdlSetPaperSource", 0),
        "page": capture("pdbdlBeginPage", attributes),
        "prepare": capture("pdbdlPrepareHalftoneImage"),
        "band": capture("pdbdlTransferHalftoneImage", 4992, 32, 0, 64, 3, 4, blob),
        "pdbdlEndPage": capture("pdbdlEndPage"), "pdbdlEndMedia": capture("pdbdlEndMedia"),
        "pdbdlEndJob": capture("pdbdlEndJob"),
    }
    expected_frames = dict(line.split("\t") for line in (fixtures / "ncap-native-frames.tsv").read_text().splitlines())
    assert {name: data.hex() for name, data in frames.items()} == expected_frames
    endings = verify_reference_page_end((root / 'reference-ncap-pdl.prn').read_bytes())
    result = {"oracle": "Canon v5.00 module and native NCAP framing functions", "driverArchiveSha256": SHA256,
              "cpcaMessagesMatched": len(fixed) - 1, "ncapFramesMatched": len(frames),
              "referenceBandEndings": endings,
              "recordedBeforeTransport": True, "physicalPrintVerified": False}
    (root / "protocol-oracle-results.json").write_text(json.dumps(result, indent=2) + "\n")
    print(json.dumps(result, indent=2))


def verify_jobs(root, jobs):
    lib = prepare(root)
    oracle = C.CDLL(str(lib / "libcanon_slimsfp.so.1.0.0"))
    byte = C.c_ubyte
    pointer = C.POINTER(byte)
    oracle.lCaptDecode.argtypes = [C.POINTER(pointer), pointer, C.c_int, C.c_int, C.POINTER(C.c_int), C.c_int, pointer]
    oracle.lCaptDecode.restype = C.c_int
    passed, bands = [], 0
    for file in sorted(jobs.glob("*.prn")):
        sw, sh, dpi, mw, mh = (file.with_suffix(".tsv").read_text().strip().split("\t"))
        sw, sh, dpi = int(sw), int(sh), int(dpi)
        assert dpi in (300, 600)
        source = file.with_suffix(".raster").read_bytes()
        source_stride = (sw + 7) // 8
        assert len(source) == source_stride * sh
        packets = cpca_packets(file.read_bytes())
        assert packets[0][0] == 0x6b and packets[-1] == (0x13, bytes(1))
        pdl = b"".join(payload[1:] for command, payload in packets if command == 0x1a)
        assert all(payload[0] == 1 for command, payload in packets if command == 0x1a)
        assert pdl[:20] == bytes.fromhex("01c18510001089c200d8840258dd80c8f0840800")
        assert pdl[20:22] == bytes.fromhex("02c3") and pdl[23:33] == bytes.fromhex("c500c60051f20003e785")
        width, height = struct.unpack_from(">HH", pdl, 33)
        assert width == (int(float(mw) / 25.4 * 600) + 127) // 128 * 128
        assert height == math.floor(float(mh) / 25.4 * 600 + 0.5)
        assert pdl[37:54] == bytes.fromhex("de8000c800caa10000cb0061e68002e500")
        offset, expected_y = 54, 0
        landscape, scale = sw > sh, 600 // dpi
        media_width = int(float(mw) / 25.4 * 600)
        # Build expected packed pixels independently, using a byte lookup and row
        # replication. Landscape is first rotated as a one-bit source image.
        if landscape:
            rw, rh = sh, sw
            rotated_stride = (rw + 7) // 8
            rotated = bytearray(rotated_stride * rh)
            for y in range(sh):
                for x in range(sw):
                    if source[y * source_stride + x // 8] & (128 >> (x % 8)):
                        tx, ty = sh - 1 - y, x
                        rotated[ty * rotated_stride + tx // 8] |= 128 >> (tx % 8)
            source, source_stride, sw, sh = rotated, rotated_stride, rw, rh
        lookup = []
        for value in range(256):
            packed = 0
            for bit in range(7, -1, -1):
                for _ in range(scale):
                    packed = (packed << 2) | (3 if value & (1 << bit) else 0)
            lookup.append(packed.to_bytes(2 * scale, "big"))
        expected_rows = []
        for y in range(sh):
            row = b"".join(lookup[v] for v in source[y * source_stride:(y + 1) * source_stride])
            # Drop any expanded one-bit source padding and clear the last media pixel.
            row = bytearray(row[:width // 4].ljust(width // 4, b"\0"))
            for x in range(min(sw * scale, media_width), width):
                row[x // 4] &= ~(3 << (6 - 2 * (x % 4)))
            expected_rows.append(bytes(row))
        while expected_y < height:
            assert pdl[offset:offset + 3] == bytes.fromhex("62e385")
            bw, rows = struct.unpack_from(">HH", pdl, offset + 3)
            assert bw == width and 1 <= rows <= 32 and expected_y + rows <= height
            assert pdl[offset + 7:offset + 11] == bytes.fromhex("e8a50000")
            assert struct.unpack_from(">H", pdl, offset + 11)[0] == expected_y
            assert pdl[offset + 13:offset + 17] == bytes.fromhex("e103d784")
            length = struct.unpack_from(">H", pdl, offset + 17)[0]
            assert pdl[offset + 19] == 0x9d and struct.unpack_from(">H", pdl, offset + 20)[0] == length
            payload = pdl[offset + 22:offset + 22 + length]
            last = expected_y + rows == height
            assert len(payload) == length and payload[:8] == bytes.fromhex("0309060100005000") and payload[-1] == 0x80
            assert payload[8] == (0 if last else 1), 'Incorrect final-band continuation flag'
            encoded = payload[13:-1]
            assert slim_end_code(encoded) == int(last), 'Incorrect SLIM page termination'
            assert struct.unpack_from("<I", payload, 9)[0] == len(encoded) + 4
            params = (byte * 8).from_buffer_copy(payload[:8])
            incoming = (byte * (len(encoded) + 8)).from_buffer_copy(encoded + bytes(8))
            start = C.cast(incoming, pointer)
            raw_size = width // 4 * rows
            outgoing = (byte * (raw_size + 16))(*([0xaa] * (raw_size + 16)))
            remaining = C.c_int(len(encoded))
            assert oracle.lCaptDecode(C.byref(start), outgoing, width // 4, rows, C.byref(remaining), 2, params) == rows
            assert bytes(outgoing[raw_size:]) == bytes([0xaa] * 16), "Decoder overrun"
            expected = b"".join(expected_rows[y // scale] if y // scale < sh else bytes(width // 4) for y in range(expected_y, expected_y + rows))
            assert bytes(outgoing[:raw_size]) == expected, (file.name, expected_y, "Decoded pixels differ")
            assert 0 <= remaining.value <= 4
            expected_y += rows
            offset += 22 + length
            bands += 1
        assert pdl[offset:] == bytes.fromhex("131211"), "Incorrect page/job termination"
        passed.append({"job": file.name, "width": width, "height": height, "bytes": file.stat().st_size})
        print("Canon native decoder verified all pixels:", file.name, flush=True)
    assert len(passed) == 12, "Missing Android-generated printer jobs"
    result = {"oracle": "Canon v5.00 lCaptDecode", "driverArchiveSha256": SHA256,
              "jobs": passed, "bandsDecoded": bands, "everyPixelCompared": True, "physicalPrintVerified": False}
    (root / "android-jobs-oracle-results.json").write_text(json.dumps(result, indent=2) + "\n")
    print(json.dumps(result, indent=2))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=["prepare", "generate", "verify-slim", "verify-protocol", "verify-jobs", "verify-mlp"])
    parser.add_argument("--work-dir", type=Path, required=True, help="External scratch directory; driver binaries must not be committed")
    parser.add_argument("--jobs-dir", type=Path, help="Android-generated complete print jobs (verify-jobs only)")
    args = parser.parse_args()
    root = args.work_dir.expanduser().resolve()
    if root == HERE or HERE in root.parents:
        parser.error("Use a scratch directory outside tools/canon")
    if args.action == "verify-mlp":
        lib = prepare(root)
        env = os.environ | {"LD_LIBRARY_PATH": str(lib) + ":" + str(lib / "Canon/CUPS_SFPR/Bidi") + ":" + str(lib / "Canon/CUPS_SFPR/Libs")}
        subprocess.run(["python3", str(HERE / "mlp_oracle.py"), str(root)], env=env, check=True, timeout=60)
    elif args.action == "verify-jobs":
        if not args.jobs_dir:
            parser.error("verify-jobs requires --jobs-dir")
        verify_jobs(root, args.jobs_dir.resolve())
    else:
        {"prepare": prepare, "generate": generate, "verify-slim": verify_slim, "verify-protocol": verify_protocol}[args.action](root)


if __name__ == "__main__":
    main()
